version: "3"
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  clients:
    build: ./clients
    ports:
      - "5173:5173"
    env_file:
      - ./clients/.env

  mongo:
    image: mongo
    ports:
      - "27017:27017"
