name: Frontend CI

on:
  push:
    paths:
      - 'client/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint || echo "Lint failed, continuing"

      - name: Build
        run: npm run build
